# Generated by Django 5.0.3 on 2024-03-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userdetail_google_auth_token_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='google_auth_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
