# Generated by Django 5.0.3 on 2024-03-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userdetail_google_auth_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
